version: '3.8'
services:
  gateway:
    build: gateway
    image: gataway-image
    container_name: gateway-container
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    image: server-image
    container_name: server-container
    ports:
      - "9091:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit

  db:
    image: postgres:14-alpine
    container_name: db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_NAME=admin
      - POSTGRES_DB=db