drop table if exists users, items, bookings, requests, comments cascade;

CREATE TABLE IF NOT EXISTS users (
id    INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name  VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS requests (
id           INT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
description  VARCHAR(512)  NOT NULL,
requestor_id INT           NOT NULL,
created      TIMESTAMP WITHOUT TIME ZONE,
FOREIGN KEY (requestor_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS items (
id          INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name        VARCHAR(255) NOT NULL,
description VARCHAR(512) NOT NULL,
available   BOOLEAN      NOT NULL,
owner_id    INT,
request_id  INT,
FOREIGN KEY (owner_id)   REFERENCES users (id),
FOREIGN KEY (request_id) REFERENCES requests (id)
);

CREATE TABLE IF NOT EXISTS bookings (
id          INT                         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
start_date  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
end_date    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
item_id     INT                         NOT NULL,
booker_id   INT                         NOT NULL,
status      INT                         NOT NULL,
FOREIGN KEY (item_id)   REFERENCES items (id),
FOREIGN KEY (booker_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS comments (
id        INT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
text      VARCHAR(512)  NOT NULL,
item_id   INT           NOT NULL,
author_id INT           NOT NULL,
FOREIGN KEY (item_id)   REFERENCES items (id),
FOREIGN KEY (author_id) REFERENCES users (id)
);